name: Deploy - Vercel

on:
  workflow_call:
    secrets:
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_TOKEN:
        required: true

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VITE_ENVIRONMENT: 'staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Node
        uses: ./.github/actions/setup-node

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Install Vercel CLI and Deploy to Vercel (Production)
        uses: ./.github/actions/deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
