name: Deploy - Netlify

on:
  workflow_call:

jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      VITE_ENVIRONMENT: 'development'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Node
        uses: ./.github/actions/setup-node

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        timeout-minutes: 1
