name: Deploy - AWS

on:
  push:
    branches:
      - master

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    env:
      VITE_ENVIRONMENT: 'production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Node
        uses: ./.github/actions/setup-node

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: aws s3 sync dist/ s3://zinko-ofed
