name: Build and Deploy to Vercel Preview
on:
  pull_request:
    branches:
      - master

jobs:
  pr-check:
    runs-on: ubuntu-22.04
    environment:
      name: 'Preview'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node and install dependencies
        uses: ./.github/actions/setup-node

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Install Vercel CLI and Deploy to Vercel (Preview)
        uses: ./.github/actions/deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          mode: 'preview'
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
